/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/impact': typeof ImpactRoute
  '/media': typeof MediaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/what-we-do': typeof WhatWeDoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/impact': typeof ImpactRoute
  '/media': typeof MediaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/what-we-do': typeof WhatWeDoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/impact': typeof ImpactRoute
  '/media': typeof MediaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/what-we-do': typeof WhatWeDoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/impact'
    | '/media'
    | '/sitemap.xml'
    | '/volunteer'
    | '/what-we-do'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/impact'
    | '/media'
    | '/sitemap.xml'
    | '/volunteer'
    | '/what-we-do'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/impact'
    | '/media'
    | '/sitemap.xml'
    | '/volunteer'
    | '/what-we-do'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  ImpactRoute: typeof ImpactRoute
  MediaRoute: typeof MediaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VolunteerRoute: typeof VolunteerRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  ImpactRoute: ImpactRoute,
  MediaRoute: MediaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VolunteerRoute: VolunteerRoute,
  WhatWeDoRoute: WhatWeDoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
